repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
  - repo: https://github.com/prettier/prettier
    rev: "master" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
  - repo: https://github.com/motet-a/jinjalint
    rev: "master" # select a tag / sha to point at
    hooks:
      - id: jinjalint
