version: "3"
services:
  datacube-ows-tools:
    build: .
    volumes:
      - .:/opt/odc/datacube-ows-tools
      - static_volume:/opt/odc/datacube-ows-tools/datacube-ows-tools/static # <-- bind the static volume
      - media_volume:/opt/odc/datacube-ows-tools/datacube-ows-tools/media # <-- bind the media volume
    networks:
      - nginx_network

  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/odc/datacube-ows-tools/datacube-ows-tools/static # <-- bind the static volume
      - media_volume:/opt/odc/datacube-ows-tools/datacube-ows-tools/media # <-- bind the media volume
    depends_on:
      - datacube-ows-tools
    networks: # <-- here
      - nginx_network

networks: # <-- and here
  nginx_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume: # <-- declare the static volume
  media_volume: # <-- declare the media volume
