name: OWS build and push

on:
  push:
    branches: [master]
    paths-ignore:
      - "docs/**"
      - "README.rst"
  pull_request:
    branches: [master]
    types: [synchronize, opened, reopened, ready_for_review]
    paths-ignore:
      - "docs/**"
      - "README.rst"
  release:
    types: [created, edited]

env:
  ORG: opendatacube
  IMAGE: dea-web-tools

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Export Secrets to enviroment
        run: |
          echo "${{ secrets.DockerPassword }}" | docker login -u "${{ secrets.DockerUser }}" --password-stdin

      - name: Push to DockerHub (master branch or tagged release only)
        if: github.ref == 'refs/heads/master' || github.event_name == 'release'
        run: |
          # figure out extra tag
          git fetch --prune --unshallow 2> /dev/null || true
          tag=$(git describe --tags)
          # build local docker image
          docker build -t ${ORG}/${IMAGE}:latest .
          # tag and push images
          docker tag ${ORG}/${IMAGE}:latest ${ORG}/${IMAGE}:${tag}
          docker push ${ORG}/${IMAGE}:latest
          docker push ${ORG}/${IMAGE}:${tag}
